[tools]
python = "3.13.2"
flutter = "3.22.2-stable"
"gem:cocoapods" = "1.16.2"
ruby = "3.3.0"
node = "22.14.0"
deno = "1.44.2"
go = "1.23.4"
rust = "stable"
java = "liberica-8u442+7"
scala = "3.6.4"
kotlin = "latest"
gradle = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby", "node"]

[env]
CLAUDE_CODE_USE_VERTEX=1
CLOUD_ML_REGION="us-east5"
ANTHROPIC_VERTEX_PROJECT_ID="c-630-ms-dev-ai-playground"
