[tools]
python = "3.13.2"
flutter = "3.22.2-stable"
"gem:cocoapods" = "1.16.2"
ruby = "3.3.0"
node = "22.14.0"
deno = "1.44.2"
go = "1.23.4"
rust = "stable"
java = "adoptopenjdk-jre-23.0.1+11"

[settings]
experimental = true
