[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[aws]
disabled = true

[gcloud]
disabled = true

[username]
disabled = true

[time]
disabled = false

[jobs]
disabled = true
